import React, { useEffect, useMemo, useState } from "react";
import { addDoc, collection, deleteDoc, doc, getDocs, orderBy, query, serverTimestamp, updateDoc } from "firebase/firestore";
import { Check, Download, IndianRupee, Plus, Upload, Users, X } from "lucide-react";
import { db } from "../../firebase";
import type { HrmsCompany, HrmsWorkspaceUser } from "../../types/hrms";

type Tab = "employees" | "attendance" | "leave" | "payroll" | "billing";
type Row = Record<string, any> & { id: string };
const field = "w-full rounded-xl border border-white/10 bg-slate-900 px-3 py-2 text-sm outline-none focus:border-cyan-400";

export default function HrmsOperations({ user, company }: { user: HrmsWorkspaceUser; company: HrmsCompany | null }) {
  const [tab,setTab]=useState<Tab>("employees"); const [rows,setRows]=useState<Row[]>([]); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  const [employee,setEmployee]=useState({name:"",email:"",phone:"",department:"",designation:"",monthlySalary:""});
  const path = useMemo(()=>user.companyId,[user.companyId]);
  const collectionName = tab === "leave" ? "leaveRequests" : tab === "payroll" ? "payrollRuns" : tab;
  const load=async()=>{if(!path||tab==="billing")return setRows([]);try{const snap=await getDocs(query(collection(db,"hrmsCompanies",path,collectionName),orderBy("createdAt","desc")));setRows(snap.docs.map(d=>({id:d.id,...d.data()})));}catch{const snap=await getDocs(collection(db,"hrmsCompanies",path,collectionName));setRows(snap.docs.map(d=>({id:d.id,...d.data()})));}};
  useEffect(()=>{load()},[path,collectionName,tab]);
  const addEmployee=async(e:React.FormEvent)=>{e.preventDefault();if(!path)return;setBusy(true);try{await addDoc(collection(db,"hrmsCompanies",path,"employees"),{...employee,monthlySalary:Number(employee.monthlySalary||0),status:"active",companyId:path,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});setEmployee({name:"",email:"",phone:"",department:"",designation:"",monthlySalary:""});setNotice("Employee added successfully.");await load()}finally{setBusy(false)}};
  const importCsv=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!path)return;const lines=(await file.text()).split(/\r?\n/).filter(Boolean);const headers=lines.shift()?.split(",").map(x=>x.trim().toLowerCase())||[];setBusy(true);try{for(const line of lines){const values=line.split(",").map(x=>x.trim());const item=Object.fromEntries(headers.map((h,i)=>[h,values[i]||""]));if(item.name&&item.email)await addDoc(collection(db,"hrmsCompanies",path,"employees"),{name:item.name,email:item.email,phone:item.phone||"",department:item.department||"",designation:item.designation||"",monthlySalary:Number(item.salary||0),status:"active",companyId:path,createdAt:serverTimestamp()})}setNotice(`${lines.length} employee rows imported.`);await load()}finally{setBusy(false);e.target.value=""}};
  const decide=async(row:Row,status:string)=>{if(!path)return;await updateDoc(doc(db,"hrmsCompanies",path,collectionName,row.id),{status,reviewedBy:user.uid,reviewedAt:serverTimestamp()});await load()};
  const runPayroll=async()=>{if(!path)return;setBusy(true);try{const employees=await getDocs(collection(db,"hrmsCompanies",path,"employees"));const month=new Date().toISOString().slice(0,7);let gross=0;const payslips=employees.docs.map(d=>{const x=d.data();const amount=Number(x.monthlySalary||0);gross+=amount;return{employeeId:d.id,employeeName:x.name,email:x.email,gross,net:amount,status:"draft"}});const run=await addDoc(collection(db,"hrmsCompanies",path,"payrollRuns"),{month,employeeCount:payslips.length,grossAmount:gross,status:"draft",createdBy:user.uid,createdAt:serverTimestamp()});for(const slip of payslips)await addDoc(collection(db,"hrmsCompanies",path,"payrollRuns",run.id,"payslips"),{...slip,gross:slip.net,createdAt:serverTimestamp()});setNotice(`Payroll draft generated for ${payslips.length} employees.`);await load()}finally{setBusy(false)}};
  const downloadPayslip=(row:Row)=>{const html=`<html><body style="font-family:Arial;padding:36px"><h1>AIJOBS HRMS Payslip</h1><h2>${company?.companyName||"Company"}</h2><p>Payroll month: ${row.month||""}</p><p>Employees: ${row.employeeCount||0}</p><p>Gross payroll: ₹${Number(row.grossAmount||0).toLocaleString("en-IN")}</p><p>Status: ${row.status||"draft"}</p></body></html>`;const blob=new Blob([html],{type:"text/html"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`payroll-${row.month||row.id}.html`;a.click();URL.revokeObjectURL(a.href)};
  const tabs:[Tab,string][]=[["employees","Employees"],["attendance","Attendance"],["leave","Leave"],["payroll","Payroll"],["billing","Subscription"]];
  return <section className="rounded-2xl border border-white/10 bg-slate-950/70 overflow-hidden"><div className="flex gap-1 overflow-x-auto border-b border-white/10 p-2">{tabs.map(([id,label])=><button key={id} onClick={()=>{setTab(id);setNotice("")}} className={`px-4 py-2 rounded-xl text-xs font-bold whitespace-nowrap ${tab===id?"bg-blue-600":"text-slate-400 hover:bg-white/5"}`}>{label}</button>)}</div><div className="p-5">
    {notice&&<p className="mb-4 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-3 text-xs text-emerald-300">{notice}</p>}
    {tab==="employees"&&<><form onSubmit={addEmployee} className="grid md:grid-cols-3 gap-3 mb-5"><input required className={field} placeholder="Employee name" value={employee.name} onChange={e=>setEmployee({...employee,name:e.target.value})}/><input required type="email" className={field} placeholder="Work email" value={employee.email} onChange={e=>setEmployee({...employee,email:e.target.value})}/><input className={field} placeholder="Phone" value={employee.phone} onChange={e=>setEmployee({...employee,phone:e.target.value})}/><input className={field} placeholder="Department" value={employee.department} onChange={e=>setEmployee({...employee,department:e.target.value})}/><input className={field} placeholder="Designation" value={employee.designation} onChange={e=>setEmployee({...employee,designation:e.target.value})}/><input type="number" className={field} placeholder="Monthly salary" value={employee.monthlySalary} onChange={e=>setEmployee({...employee,monthlySalary:e.target.value})}/><button disabled={busy} className="rounded-xl bg-blue-600 py-2 text-sm font-bold"><Plus className="inline w-4 h-4 mr-1"/>Add Employee</button><label className="cursor-pointer rounded-xl border border-cyan-400/30 py-2 text-center text-sm text-cyan-300"><Upload className="inline w-4 h-4 mr-1"/>Import CSV<input type="file" accept=".csv" className="hidden" onChange={importCsv}/></label><p className="text-[11px] text-slate-500 self-center">CSV: name,email,phone,department,designation,salary</p></form></>}
    {tab==="payroll"&&<button disabled={busy} onClick={runPayroll} className="mb-5 rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-bold"><IndianRupee className="inline w-4 h-4"/> Generate Monthly Payroll</button>}
    {tab==="billing"?<div className="grid md:grid-cols-2 gap-4"><div className="rounded-2xl border border-cyan-400/30 bg-cyan-500/10 p-5"><p className="text-xs text-cyan-300">CURRENT PLAN</p><h3 className="text-2xl font-black capitalize mt-2">{company?.plan?.replace("_"," ")||"Starter"}</h3><p className="text-sm text-slate-400 mt-1">Status: {company?.status||"trial"}</p><p className="text-sm text-slate-400">Trial ends: {company?.trialEndsAt?new Date(company.trialEndsAt).toLocaleDateString("en-IN"):"—"}</p></div><div className="rounded-2xl border border-white/10 p-5"><h3 className="font-bold">Upgrade / Activate</h3><p className="text-sm text-slate-400 mt-2">Online payment activation requires your Razorpay merchant keys. Until configured, sales can activate plans from the AIJOBS admin account after payment verification.</p><a href="mailto:infoaisoft26@gmail.com?subject=AIJOBS HRMS Plan Activation" className="inline-block mt-4 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold">Contact Sales</a></div></div>:<div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="text-xs text-slate-500"><tr><th className="pb-3">Name / Record</th><th className="pb-3">Details</th><th className="pb-3">Status</th><th className="pb-3 text-right">Action</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-white/5"><td className="py-3 font-semibold">{r.name||r.employeeName||r.month||r.date||r.id.slice(0,8)}</td><td className="py-3 text-xs text-slate-400">{r.email||r.department||r.reason||`${r.employeeCount||0} employees`}</td><td className="py-3"><span className="rounded-full bg-white/5 px-2 py-1 text-xs">{r.status||"pending"}</span></td><td className="py-3 text-right">{(tab==="leave"||tab==="attendance")&&r.status!=="approved"&&<><button onClick={()=>decide(r,"approved")} title="Approve" className="p-2 text-emerald-400"><Check className="w-4 h-4"/></button><button onClick={()=>decide(r,"rejected")} title="Reject" className="p-2 text-red-400"><X className="w-4 h-4"/></button></>}{tab==="employees"&&<button onClick={async()=>{if(path){await deleteDoc(doc(db,"hrmsCompanies",path,"employees",r.id));load()}}} className="text-xs text-red-400">Deactivate</button>}{tab==="payroll"&&<button onClick={()=>downloadPayslip(r)} className="p-2 text-cyan-300"><Download className="w-4 h-4"/></button>}</td></tr>)}{!rows.length&&<tr><td colSpan={4} className="py-12 text-center text-slate-500"><Users className="w-8 h-8 mx-auto mb-2"/>No records yet.</td></tr>}</tbody></table></div>}
  </div></section>;
}
