import React, { useEffect, useState } from "react";
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from "firebase/auth";
import { collection, doc, getCountFromServer, getDoc, setDoc } from "firebase/firestore";
import { Building2, Check, Clock3, FileText, Fingerprint, IndianRupee, LayoutDashboard, LogIn, ShieldCheck, UserPlus, Users, WalletCards } from "lucide-react";
import { auth, db } from "../../firebase";
import type { HrmsCompany, HrmsPlan, HrmsWorkspaceUser } from "../../types/hrms";
import HrmsOperations from "./HrmsOperations";

const modules = [
  [Users, "Employee Directory", "Employee lifecycle, departments, documents and onboarding."],
  [Fingerprint, "Attendance & Shifts", "Mobile check-in, geofence, shifts, late marks and regularization."],
  [Clock3, "Leave Management", "Leave balances, approvals, holiday calendar and team availability."],
  [WalletCards, "Payroll & Payslips", "Attendance-linked payroll, deductions, approvals and payslip history."],
  [FileText, "Documents & Compliance", "Offer letters, employee documents, policies and audit trail."],
  [LayoutDashboard, "HR Analytics", "Headcount, attendance, attrition, payroll and workforce reports."]
] as const;

export function HrmsLanding({ onLogin, onRegister, onBack }: { onLogin: () => void; onRegister: () => void; onBack: () => void }) {
  return <div className="min-h-screen bg-[#061127] text-white px-5 py-8">
    <div className="max-w-6xl mx-auto space-y-12">
      <nav className="flex items-center justify-between">
        <button onClick={onBack} className="text-sm font-bold text-cyan-300">AIJOBS</button>
        <div className="flex gap-2"><button onClick={onLogin} className="px-4 py-2 border border-white/15 rounded-xl text-xs">HRMS Login</button><button onClick={onRegister} className="px-4 py-2 bg-blue-600 rounded-xl text-xs font-bold">Start Free Trial</button></div>
      </nav>
      <section className="grid lg:grid-cols-2 gap-10 items-center py-8">
        <div className="space-y-5"><span className="text-xs text-cyan-300 font-bold tracking-widest">AIJOBS HRMS • MULTI-COMPANY CLOUD SOFTWARE</span><h1 className="text-4xl md:text-6xl font-black leading-tight">Run your entire workforce from one secure HRMS.</h1><p className="text-slate-300 text-lg">Attendance, leave, payroll, onboarding and employee self-service—plus an optional AIJOBS recruitment bundle.</p><div className="flex flex-wrap gap-3"><button onClick={onRegister} className="px-6 py-3 bg-gradient-to-r from-blue-600 to-cyan-500 rounded-xl font-bold">Create Company Workspace</button><button onClick={onLogin} className="px-6 py-3 border border-blue-400/30 rounded-xl">Company / Employee Login</button></div><div className="flex flex-wrap gap-4 text-xs text-slate-400"><span>✓ 14-day trial</span><span>✓ No card required</span><span>✓ India payroll-ready</span></div></div>
        <div className="rounded-3xl border border-blue-400/20 bg-white/5 p-6 shadow-2xl"><div className="grid grid-cols-2 gap-3">{["Live Headcount","Present Today","Leave Requests","Payroll Ready"].map((x,i)=><div key={x} className="rounded-2xl bg-slate-950/70 border border-white/10 p-4"><p className="text-xs text-slate-400">{x}</p><p className="text-2xl font-black mt-2">{[248,221,8,"₹32.4L"][i]}</p></div>)}</div><div className="mt-4 h-36 rounded-2xl bg-gradient-to-br from-blue-600/20 to-cyan-500/5 border border-cyan-400/20 flex items-end gap-2 p-5">{[35,70,48,85,62,92,78].map((h,i)=><div key={i} className="flex-1 rounded-t bg-gradient-to-t from-blue-600 to-cyan-400" style={{height:`${h}%`}} />)}</div></div>
      </section>
      <section><h2 className="text-2xl font-black text-center mb-7">Complete HR operations suite</h2><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">{modules.map(([Icon,title,desc])=><div key={title} className="p-5 rounded-2xl bg-white/5 border border-white/10"><Icon className="w-6 h-6 text-cyan-400"/><h3 className="font-bold mt-3">{title}</h3><p className="text-sm text-slate-400 mt-1">{desc}</p></div>)}</div></section>
      <section className="grid md:grid-cols-3 gap-4 pb-14">{[
        ["Starter","₹49","employee / month",["Core HR","Attendance","Leave","Employee self-service"]],
        ["Growth","₹99","employee / month",["Everything in Starter","Payroll & payslips","Documents","HR analytics"]],
        ["Recruitment Bundle","Custom","annual plan",["Complete HRMS","AIJOBS recruitment","Candidate pipeline","Priority onboarding"]]
      ].map(([name,price,unit,items])=><div key={String(name)} className={`p-6 rounded-2xl border ${name==="Growth"?"border-cyan-400 bg-cyan-500/10":"border-white/10 bg-white/5"}`}><h3 className="font-black text-xl">{name}</h3><p className="text-3xl font-black mt-4">{price}</p><p className="text-xs text-slate-400">{unit}</p><div className="space-y-2 mt-5">{(items as string[]).map(i=><p key={i} className="text-sm flex gap-2"><Check className="w-4 h-4 text-emerald-400"/>{i}</p>)}</div></div>)}</section>
    </div>
  </div>;
}

function AuthShell({ title, children, onBack }: { title: string; children: React.ReactNode; onBack: () => void }) {
  return <div className="min-h-screen bg-[#061127] text-white grid place-items-center p-5"><div className="w-full max-w-md rounded-3xl bg-slate-950/80 border border-blue-400/20 p-6 shadow-2xl"><button onClick={onBack} className="text-xs text-cyan-300 mb-5">← Back to HRMS</button><div className="flex items-center gap-3 mb-5"><div className="w-11 h-11 rounded-xl bg-blue-600/20 grid place-items-center"><Building2 className="text-cyan-400"/></div><div><p className="font-black">AIJOBS HRMS</p><h1 className="text-sm text-slate-400">{title}</h1></div></div>{children}</div></div>;
}

const inputClass = "w-full px-3 py-2.5 bg-slate-900 border border-white/10 rounded-xl text-sm outline-none focus:border-cyan-400";

export function HrmsRegister({ onSuccess, onBack }: { onSuccess: (user: HrmsWorkspaceUser) => void; onBack: () => void }) {
  const [form,setForm]=useState({companyName:"",name:"",email:"",phone:"",password:"",employeeRange:"1-25",plan:"starter" as HrmsPlan}); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const cred=await createUserWithEmailAndPassword(auth,form.email.trim(),form.password);const now=new Date();const trial=new Date(now.getTime()+14*86400000);const companyId=`hrms_${cred.user.uid}`;const company:HrmsCompany={id:companyId,companyName:form.companyName.trim(),ownerUid:cred.user.uid,ownerEmail:form.email.trim(),phone:form.phone.trim(),employeeRange:form.employeeRange,plan:form.plan,status:"trial",trialEndsAt:trial.toISOString(),createdAt:now.toISOString(),updatedAt:now.toISOString()};const user:HrmsWorkspaceUser={uid:cred.user.uid,name:form.name.trim(),email:form.email.trim(),role:"hrms_admin",companyId};await Promise.all([setDoc(doc(db,"hrmsCompanies",companyId),company),setDoc(doc(db,"users",cred.user.uid),{...user,companyName:company.companyName,status:"active",createdAt:now.toISOString()},{merge:true}),setDoc(doc(db,"hrmsCompanies",companyId,"members",cred.user.uid),user)]);onSuccess(user);}catch(err:any){setError(err?.code==="auth/email-already-in-use"?"This email is already registered. Please sign in.":err.message||"Company registration failed.");}finally{setBusy(false)}};
  return <AuthShell title="Create company workspace" onBack={onBack}><form onSubmit={submit} className="space-y-3"><input required className={inputClass} placeholder="Company name" value={form.companyName} onChange={e=>setForm({...form,companyName:e.target.value})}/><input required className={inputClass} placeholder="HR / Owner full name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/><input required type="email" className={inputClass} placeholder="Work email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className={inputClass} placeholder="Phone number" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><div className="grid grid-cols-2 gap-3"><select className={inputClass} value={form.employeeRange} onChange={e=>setForm({...form,employeeRange:e.target.value})}><option>1-25</option><option>26-100</option><option>101-500</option><option>500+</option></select><select className={inputClass} value={form.plan} onChange={e=>setForm({...form,plan:e.target.value as HrmsPlan})}><option value="starter">Starter</option><option value="growth">Growth</option><option value="recruitment_bundle">Recruitment Bundle</option></select></div><input required minLength={8} type="password" className={inputClass} placeholder="Password (minimum 8 characters)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/>{error&&<p className="text-xs text-red-300">{error}</p>}<button disabled={busy} className="w-full py-3 bg-blue-600 rounded-xl font-bold disabled:opacity-50"><UserPlus className="inline w-4 h-4 mr-2"/>{busy?"Creating workspace...":"Start 14-Day Free Trial"}</button><p className="text-[11px] text-slate-500 text-center">By continuing, you agree to AIJOBS HRMS Terms and Privacy Policy.</p></form></AuthShell>;
}

export function HrmsLogin({ onSuccess, onBack }: { onSuccess: (user: HrmsWorkspaceUser) => void; onBack: () => void }) {
  const [email,setEmail]=useState("");const[password,setPassword]=useState("");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError("");try{const cred=await signInWithEmailAndPassword(auth,email.trim(),password);const snap=await getDoc(doc(db,"users",cred.user.uid));if(!snap.exists())throw new Error("HRMS profile not found.");const data=snap.data();const role=String(data.role||"");if(!["hrms_admin","employee","employer","admin","super_admin","superadmin"].includes(role))throw new Error("This account does not have HRMS access.");const isPlatformAdmin=["admin","super_admin","superadmin"].includes(role);const companyId=String(data.companyId||data.tenantId||(isPlatformAdmin?"hrms_aijobs_internal":""));if(!companyId)throw new Error("No company workspace is linked to this account.");if(isPlatformAdmin){const now=new Date().toISOString();await setDoc(doc(db,"hrmsCompanies",companyId),{id:companyId,companyName:"AIJOBS",ownerUid:cred.user.uid,ownerEmail:data.email||cred.user.email||"infoaisoft26@gmail.com",plan:"recruitment_bundle",status:"active",updatedAt:now,createdAt:data.createdAt||now},{merge:true});await setDoc(doc(db,"hrmsCompanies",companyId,"members",cred.user.uid),{uid:cred.user.uid,name:data.name||"AIJOBS Owner",email:data.email||cred.user.email||"",role:role==="superadmin"?"super_admin":role,companyId},{merge:true})}onSuccess({uid:cred.user.uid,name:data.name||cred.user.displayName||"HRMS User",email:data.email||cred.user.email||"",role:role==="superadmin"?"super_admin":role as any,companyId});}catch(err:any){setError(err?.code?.startsWith("auth/")?"Invalid email or password.":err.message||"Login failed.");}finally{setBusy(false)}};
  return <AuthShell title="Company Admin / Employee login" onBack={onBack}><form onSubmit={submit} className="space-y-3"><input required type="email" className={inputClass} placeholder="Work email" value={email} onChange={e=>setEmail(e.target.value)}/><input required type="password" className={inputClass} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="text-xs text-red-300">{error}</p>}<button disabled={busy} className="w-full py-3 bg-blue-600 rounded-xl font-bold disabled:opacity-50"><LogIn className="inline w-4 h-4 mr-2"/>{busy?"Verifying...":"Access HRMS Workspace"}</button><div className="p-3 rounded-xl bg-emerald-500/5 border border-emerald-500/20 text-xs text-emerald-300 flex gap-2"><ShieldCheck className="w-4 h-4 shrink-0"/>Company data remains isolated inside its own workspace.</div></form></AuthShell>;
}

export function HrmsCompanyDashboard({ user, onLogout }: { user: HrmsWorkspaceUser; onLogout: () => void }) {
  const [company,setCompany]=useState<HrmsCompany|null>(null);const[counts,setCounts]=useState({employees:0,attendance:0,leaves:0,payroll:0});
  useEffect(()=>{if(!user.companyId)return;Promise.all([getDoc(doc(db,"hrmsCompanies",user.companyId)),getCountFromServer(collection(db,"hrmsCompanies",user.companyId,"employees")),getCountFromServer(collection(db,"hrmsCompanies",user.companyId,"attendance")),getCountFromServer(collection(db,"hrmsCompanies",user.companyId,"leaveRequests")),getCountFromServer(collection(db,"hrmsCompanies",user.companyId,"payrollRuns"))]).then(([c,e,a,l,p])=>{if(c.exists())setCompany({id:c.id,...c.data()} as HrmsCompany);setCounts({employees:e.data().count,attendance:a.data().count,leaves:l.data().count,payroll:p.data().count})}).catch(console.error)},[user.companyId]);
  return <div className="min-h-screen bg-[#061127] text-white p-5"><div className="max-w-6xl mx-auto space-y-6"><header className="flex items-center justify-between"><div><p className="text-xs text-cyan-300 font-bold">AIJOBS HRMS</p><h1 className="text-2xl font-black">{company?.companyName||"Company Workspace"}</h1><p className="text-xs text-slate-400">{company?.status||"active"} • {company?.plan||"workspace"} plan</p></div><button onClick={onLogout} className="px-4 py-2 border border-white/15 rounded-xl text-xs">Logout</button></header><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{[[Users,"Employees",counts.employees],[Clock3,"Attendance Records",counts.attendance],[FileText,"Leave Requests",counts.leaves],[IndianRupee,"Payroll Runs",counts.payroll]].map(([Icon,label,value]:any)=><div key={label} className="p-5 bg-white/5 border border-white/10 rounded-2xl"><Icon className="text-cyan-400 w-5 h-5"/><p className="text-xs text-slate-400 mt-3">{label}</p><p className="text-3xl font-black">{value}</p></div>)}</div><HrmsOperations user={user} company={company}/></div></div>;
}
