import crypto from "crypto";
import type { Request, Response } from "express";
import { getFirebaseAuth, getFirestoreDb } from "./firestoreHelper.js";

const PUBLIC_EVENTS = new Set(["hire_landing_view","role_selected","registration_started","pricing_viewed"]);
const ALL_EVENTS = new Set(["hire_landing_view","role_selected","registration_started","registration_completed","company_profile_completed","job_creation_started","job_submitted","job_approved","job_rejected","first_job_credit_used","pricing_viewed","upgrade_started","upgrade_completed"]);
function clean(v:any,max=300){return String(v??"").trim().slice(0,max)}
function normalizeRole(v:any){return clean(v,30).toLowerCase().replace(/[\s-]+/g,"_")}
async function getOptionalUser(req:Request){const h=String(req.headers.authorization||"");if(!h.startsWith("Bearer "))return null;try{return await getFirebaseAuth().verifyIdToken(h.slice(7),true)}catch{return null}}
async function requireAdmin(req:Request){const decoded=await getOptionalUser(req);if(!decoded)throw Object.assign(new Error("Admin authentication required."),{status:401});const db=getFirestoreDb();const [u,a]=await Promise.all([db.collection("users").doc(decoded.uid).get(),db.collection("admins").doc(decoded.uid).get()]);const role=normalizeRole(u.data()?.role||decoded.role);if(!(role==="admin"||role==="superadmin"||role==="super_admin"||a.exists))throw Object.assign(new Error("Admin access required."),{status:403});return{decoded,db}}
function attr(body:any){const a=body?.marketingAttribution||body||{};return{source:clean(a.source||a.utm_source,100),medium:clean(a.medium||a.utm_medium,100),campaign:clean(a.campaign||a.utm_campaign,160),content:clean(a.content||a.utm_content,160),term:clean(a.term||a.utm_term,160),gclid:clean(a.gclid,256),fbclid:clean(a.fbclid,256),landingPage:clean(a.landingPage,500),referrer:clean(a.referrer,500)}}

export async function handleHiringAnalyticsRoute(req:Request,res:Response):Promise<boolean>{
  const path=String(req.url||"").split("?")[0].replace(/\/+$/,"")||"/";
  if(path!=="/api/hire/event"&&path!=="/api/hire/admin/analytics-v2")return false;
  try{
    if(path==="/api/hire/event"){
      if(req.method!=="POST"){res.status(405).json({success:false,error:"Method not allowed."});return true}
      const eventName=clean(req.body?.eventName,80);if(!ALL_EVENTS.has(eventName)){res.status(400).json({success:false,error:"Unsupported event."});return true}
      const decoded=await getOptionalUser(req);if(!decoded&&!PUBLIC_EVENTS.has(eventName)){res.status(401).json({success:false,error:"Authentication required for this event."});return true}
      const visitorId=clean(req.body?.visitorId,120)||decoded?.uid||"anonymous";const attribution=attr(req.body);const day=new Date().toISOString().slice(0,10);const dedupeSeed=clean(req.body?.dedupeKey,300)||`${eventName}:${decoded?.uid||visitorId}:${attribution.landingPage||"/hire"}:${eventName==="hire_landing_view"?day:"once"}`;const id=`evt_${crypto.createHash("sha256").update(dedupeSeed).digest("hex").slice(0,32)}`;const db=getFirestoreDb(),ref=db.collection("marketingEvents").doc(id),snap=await ref.get();if(!snap.exists)await ref.set({id,eventName,uid:decoded?.uid||null,visitorId,role:normalizeRole(req.body?.role),marketingAttribution:attribution,...attribution,createdAt:new Date().toISOString()});res.json({success:true,deduped:snap.exists});return true
    }
    if(path==="/api/hire/admin/analytics-v2"){
      if(req.method!=="GET"){res.status(405).json({success:false,error:"Method not allowed."});return true}
      const {db}=await requireAdmin(req);const [eventsSnap,usersSnap,jobsSnap]=await Promise.all([db.collection("marketingEvents").get(),db.collection("users").get(),db.collection("jobs").get()]);const events=eventsSnap.docs.map(d=>d.data() as any);const hiringUsers=usersSnap.docs.map(d=>d.data() as any).filter(u=>["employer","recruiter","consultancy"].includes(normalizeRole(u.role)));const jobs=jobsSnap.docs.map(d=>d.data() as any);const visitors=new Set(events.filter(e=>e.eventName==="hire_landing_view").map(e=>e.visitorId||e.id));const paidConversions=events.filter(e=>e.eventName==="upgrade_completed").length;const byCampaign:Record<string,any>={};for(const e of events){const a=e.marketingAttribution||e;const key=[a.source||"direct",a.medium||"none",a.campaign||"none",a.content||"none"].join(" | ");byCampaign[key]||={source:a.source||"direct",medium:a.medium||"none",campaign:a.campaign||"none",content:a.content||"none",landingViews:0,registrationStarted:0,registrations:0,firstJobsSubmitted:0,jobsApproved:0,jobsRejected:0,paidConversions:0};const row=byCampaign[key];if(e.eventName==="hire_landing_view")row.landingViews++;if(e.eventName==="registration_started")row.registrationStarted++;if(e.eventName==="registration_completed")row.registrations++;if(e.eventName==="job_submitted")row.firstJobsSubmitted++;if(e.eventName==="job_approved")row.jobsApproved++;if(e.eventName==="job_rejected")row.jobsRejected++;if(e.eventName==="upgrade_completed")row.paidConversions++}for(const r of Object.values(byCampaign) as any[]){r.visitorToRegistrationRate=r.landingViews?Number(((r.registrations/r.landingViews)*100).toFixed(1)):0;r.registrationToApprovedRate=r.registrations?Number(((r.jobsApproved/r.registrations)*100).toFixed(1)):0}res.json({success:true,totals:{landingPageVisitors:visitors.size,registrations:hiringUsers.length,employerRegistrations:hiringUsers.filter(u=>normalizeRole(u.role)==="employer").length,recruiterRegistrations:hiringUsers.filter(u=>normalizeRole(u.role)==="recruiter").length,consultancyRegistrations:hiringUsers.filter(u=>normalizeRole(u.role)==="consultancy").length,firstJobsSubmitted:events.filter(e=>e.eventName==="job_submitted").length,jobsApproved:jobs.filter(j=>normalizeRole(j.status)==="approved").length,jobsRejected:jobs.filter(j=>normalizeRole(j.status)==="rejected").length,paidConversions},byCampaign:Object.values(byCampaign)});return true
    }
    return false
  }catch(error:any){res.status(Number(error?.status||500)).json({success:false,error:error?.message||"Analytics request failed."});return true}
}
