import React from "react";
import { BadgeCheck, BrainCircuit, FileCheck2, LockKeyhole, SearchCheck, UserRoundSearch } from "lucide-react";
import { motion, useReducedMotion } from "motion/react";

const benefits = [["Verified Jobs", "Explore public openings that have passed the AIJOBS approval workflow.", BadgeCheck], ["AI Job Matching", "Use your skills and preferences to discover more relevant live roles.", BrainCircuit], ["Quick Apply", "Move from discovery to application through the existing candidate flow.", FileCheck2], ["Secure Candidate Profile", "Keep your career details and application activity in one protected account.", LockKeyhole], ["Free for Candidates", "Search and apply without paying AIJOBS any candidate fee.", SearchCheck], ["Better Recruiter Visibility", "A complete profile helps verified recruiters understand your experience.", UserRoundSearch]] as const;

export default function CandidateBenefits() {
  const reduceMotion = useReducedMotion();
  return <section className="bg-[#f6f9ff] py-16 sm:py-20" aria-labelledby="candidate-benefits-heading"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mx-auto max-w-2xl text-center"><p className="text-xs font-black uppercase tracking-[.2em] text-blue-600">Built for job seekers</p><h2 id="candidate-benefits-heading" className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">Everything you need for a safer job search</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(([title, description, Icon], index) => <motion.article key={title} initial={reduceMotion ? false : { opacity: 0, y: 18 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.2 }} transition={{ duration: reduceMotion ? 0 : 0.4, delay: reduceMotion ? 0 : index * 0.05 }} whileHover={reduceMotion ? undefined : { y: -6 }} className="group rounded-[1.75rem] border border-white bg-white/90 p-6 shadow-[0_18px_55px_rgba(15,23,42,.08)] ring-1 ring-slate-200/70 transition-shadow hover:shadow-[0_26px_70px_rgba(37,99,235,.15)]"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gradient-to-br from-blue-600 to-cyan-500 text-white shadow-lg shadow-blue-600/20 transition-transform group-hover:scale-105"><Icon className="h-5 w-5" /></div><h3 className="mt-5 text-lg font-black text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{description}</p></motion.article>)}</div></div></section>;
}
